### ISSUE TITLE
上拉加载有问题，

### ISSUE THREAD

**Issue by z244370114** [Othershe/RecyclerViewAdapter#1]
第一次上啦加载，还没加载完成之前。我连续上拉，会根据我上拉的次数一次性加载了多次。

**Comment by shehuan** [comment]
本次加载是否正在进行，调用者是知道的，可以根据是否正在加载来判断是否屏蔽下一次加载。当然如果要封装到adapter里也是可以的，但调用者需要主动告诉adapter当前加载是否结束，然后在adapter中屏蔽加载更多的执行。

**Comment by z244370114** [comment]
还有就是，如果用到多种类型的ITEM。有局限性了。

**Comment by shehuan** [comment]
多类型item已经支持了哦
