### ISSUE TITLE
加载更多完成后跳到了列表顶部

### ISSUE THREAD

**Issue by micki-zhou** [Othershe/RecyclerViewAdapter#10]
如上

**Comment by micki-zhou** [comment]
补充，加载更多的回调只调用了一次，第二次就没有走回调方法，然后就是设置数据后，列表跳到了顶部，代码如下

private fun initRvList(data: QwNewsListEntity) {
        rv_dynamic.layoutManager = LinearLayoutManager(context)

        if (adapter == null) {
            adapter = DynamicListAdapter(context!!, data.content!!)
            adapter?.setLoadingView(R.layout.view_load_more)
            adapter?.setLoadEndView(R.layout.view_load_more_finish)
            adapter?.setOnLoadMoreListener {
                if (adapter!!.dataCount < data.total) {
                    page++
                    getQwNews()
                } else {
                    adapter?.loadEnd()
                }
            }

            rv_dynamic.adapter = adapter

        } else {
            if (page == 1) {
                adapter?.reset()
                adapter?.setNewData(data.content)
            } else
                adapter?.setLoadMoreData(data.content)
        }
    }

**Comment by shehuan** [comment]
你这写法有点乱呀

**Comment by micki-zhou** [comment]
private fun initRvList(data: QwNewsListEntity) {
        rv_dynamic.layoutManager = LinearLayoutManager(context)

        if (adapter == null) { 
            // adapter 初始化
            adapter = DynamicListAdapter(context!!, data.content!!)
            adapter?.setLoadingView(R.layout.view_load_more)
            adapter?.setLoadEndView(R.layout.view_load_more_finish)
            adapter?.setOnLoadMoreListener {
                if (adapter!!.dataCount < data.total) {
                    page++
                    getQwNews() // 请求更多数据
                } else { 
                    // 已加载完成
                    adapter?.loadEnd()
                }
            }

            rv_dynamic.adapter = adapter // 设置adapter

        } else { // 已初始化过adapter
            if (page == 1) { // 如果是第一页，重置adapter，设置新数据
                adapter?.reset()
                adapter?.setNewData(data.content)
            } else // 加载更多数据添加
                adapter?.setLoadMoreData(data.content)
        }
    }

**Comment by shehuan** [comment]
1、OnLoadMoreListener回调方法里边只是用来发起加载更多的请求的
2、在你的数据接口的回调里完成setNewData()、setLoadMoreData()、loadEnd()等

可以参考下demo的写法

**Comment by micki-zhou** [comment]
解决了，是我自己的问题，感谢开源。
