### ISSUE TITLE
添加下拉刷新的问题

### ISSUE THREAD

**Issue by MelvinCen** [Othershe/RecyclerViewAdapter#13]
如果添加下拉刷新功能，在已经加载到end情况下，去下拉刷新，调用你的哪个方法重置状态，不重置的话下拉刷新后第一页下面的footerView就是end了

**Comment by shehuan** [comment]
因为adapter记录了状态了，需要在下拉刷新前执行reset()方法

**Comment by MelvinCen** [comment]
加了下拉刷新后，先加载更多，还没完成时立刻去下拉刷新，下拉刷新还没完成时再立刻去加载更多，这时两个加载圈同时存在，这个要怎么做。 我用了一个boolean值来区分加载和下拉，还是同样的操作，但是最后的结果是只有加载更多的进度框在那边显示，而没有真正去加载更多数据

**Comment by MelvinCen** [comment]
下拉刷新我调用的顺序是reset() -> setNewData()，最后刷新完发现列表没有返回最顶部，页面的可见第一条位置不是0（下拉刷新过程中我故意往下滑了几个）
