### ISSUE TITLE
关于不满一屏无法刷新问题的解决办法

### ISSUE THREAD

**Issue by Yuven-Lee** [Othershe/RecyclerViewAdapter#14]
我的解决办法是在update第一页数据之后判断一下RecyclerView是否能滚动，不能滚动就直接显示loadEndView，这个逻辑是合理的，试想一下没有更多元素可以滚动其实已经代表了没有分页这个概念了

仔细的分析可以看下这篇文章：
[RecyclerView，你为什么不回调 onScrolled 方法了？](https://www.jianshu.com/p/02c6ad79900e)

下面是我的代码：
public void updateData(List datas) {
        if (isReset) {
            isReset = false;
        }
        isLoading = false;
        dataList.clear();
        dataList.addAll(datas);
        notifyDataSetChanged();
        //判断RecyclerView是否能滚动 不能滚动就无法触发刷新 直接显示暂无更多数据
        mRecyclerView.post(new Runnable() {
            @Override
            public void run() {
                if (!mRecyclerView.canScrollVertically(1)) {
                    loadEnd();
                }
            }
        });
    }

**Comment by shehuan** [comment]
这样处理也行，但不满一屏不代表不能继续分页了吧

**Comment by Yuven-Lee** [comment]
结合接口去考虑，如果pageSize有传的话，但是接口给的数据一屏都不满的话，没有第二页这个概念是可以成立的。

**Comment by shehuan** [comment]
你这样也是合理的
