### ISSUE TITLE
从Empty View跳转到loadFail View

### ISSUE THREAD

**Issue by langrenbule** [Othershe/RecyclerViewAdapter#3]
你好，从最开始的没有任何数据到加载失败，无法从Empty View 跳转到 LoadFail View中

**Comment by shehuan** [comment]
LoadFail View是分页加载失败的情况才出现的，初次加载失败跳转到这里并不合理

**Comment by langrenbule** [comment]
但是 如果是首次进入软件的话，一般情况下是没数据的，这个时候，是EmptyView 的loading也显示，当服务器返回 获取数据失败，界面仍停留在Empty View的loading页面.感觉不合理.

**Comment by shehuan** [comment]
代码已更新，现在可以直接移除EmptyView或者添加新View实现重新加载、提示用户

**Comment by langrenbule** [comment]
厉害了，我的哥!
