### ISSUE TITLE
有个错误，请大神帮忙看一下～

### ISSUE THREAD

**Issue by LiXgo** [Othershe/RecyclerViewAdapter#5]
我使用加载更多逻辑的时候 当我调用commonAdapter.setLoadMoreData(list);  时，如果list的长度为0的时候，会报下标越界的错误！
场景：一次加载10条数据，刚好数据有20条，所以在加载第三次的时候 服务器返回的list.size=0

**Comment by shehuan** [comment]
可以加个判断，如果list.size=0就不要调用setLoadMoreData()
