### ISSUE TITLE
有个问题

### ISSUE THREAD

**Issue by AndroidDai** [Othershe/RecyclerViewAdapter#7]
您好，我在使用你这个lib的时候，不显示加载更多或者加载完成的FooterView的时候，您的Demo最下面的item显示不完成，下面的横线看不见

**Comment by shehuan** [comment]
有截图吗

**Comment by AndroidDai** [comment]
有的，我能加你您的QQ发给你吗？

**Comment by AndroidDai** [comment]
有的，您方便给下QQ号吗？

**Comment by AndroidDai** [comment]
只要把Adapter的第三个参数设置为false就是出现这个问题。
mAdapter = new CommonRefreshAdapter(this, null, false);

**Comment by shehuan** [comment]
仔细看，横线是在的

**Comment by AndroidDai** [comment]
是有的，谢谢大神，但是还有一个问题，我试用您的这个Adapter，想要给item的CompoundButton添加滑动的监听，好像是没有，只能够监听到onClick的事件吗？

**Comment by shehuan** [comment]
Activity、Fragment里只能绑定点击事件，目前可以在Adapter里获得相应的View然后绑定事件

**Comment by AndroidDai** [comment]
谢谢耐心讲解，已经解决了。
